<?php


class Action extends Model
{
    public $table = 'actios';
    public $db_table_fields = array('id','name');
    public $id;
    public $name;

    public function delete()
    {
        global $database;
        $sql = "DELETE FROM users_action  WHERE action_id = ".$database->escape_string($this->id);

        $database->query($sql);

        return parent::delete(); // TODO: Change the autogenerated stub
    }

}