<?php


class User extends Model
{

    public $table = 'users';
    public $db_table_fields = array('id','name','email','password','role');
    public $id;
    public $name;
    public $role;
    public $email;
    public $password;

    public function login($email, $password) {
        $sql = "SELECT * FROM $this->table WHERE email = '{$email}' AND password = '{$password}' LIMIT 1";
        return $this->find_by_query($sql);
    }

    public function delete()
    {
        global $database;
        $sql = "DELETE FROM users_action  WHERE user_id = ".$database->escape_string($this->id);
        $database->query($sql);

        return parent::delete(); // TODO: Change the autogenerated stub
    }


}