<?php
require_once("config.php");
include("classes/Db.php");
include("classes/Session.php");
include("classes/Services.php");
include("classes/model/Model.php");
include("classes/model/User.php");
include("classes/model/Actin.php");
include("classes/controller/AdminController.php");
include("classes/controller/FrontController.php");